application: pacmacro
version: 4
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- channel_presence

handlers:
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /
  static_files: index.html
  upload: index.html
- url: .*
  script: main.app

